---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Configuration operator"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: configuration-operator
---
# Install Namespace Configuration operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: namespace-configuration-operator
  namespace: namespace-configuration-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: namespace-configuration-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: namespace-configuration-operator.v1.2.6
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: db-hack-user-config
spec:
  providerName: Microsoft_Entra_ID
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ .Name | replace "." "-"}}-sandbox
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: {{ .Name | replace "." "-"}}-sandbox
          namespace: {{ .Name | replace "." "-"}}-sandbox
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
        subjects:
        - kind: User
          apiGroup: rbac.authorization.k8s.io
          name: {{ .Name }}
    - objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: standard-sandbox
          namespace: {{ .Name | replace "." "-"}}-sandbox
        spec:
          hard:
            requests.cpu: "1"
            requests.memory: 1Gi
            requests.ephemeral-storage: 2Gi
---
# Install Devspaces
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspaces
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Install OpenShift AI
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhods-operator.2.10.0
---
# Install custom autoscaler
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-custom-metrics-autoscaler-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-custom-metrics-autoscaler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: custom-metrics-autoscaler.v2.12.1-394
---
# Install OpenShift Developerhub
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "RHDH"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: rhdh-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: rhdh-operator
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Install web terminal
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: web-terminal
  source: redhat-operators
  sourceNamespace: openshift-marketplace
